const products = [
    {
        id: 1,
        name: "Product One",
        title: "Mens stylish sneakers",
        description: "The men nike shoe is back and true to its iconic 3-starp design. The leather and woven upper delivers stylish confort while the mesh forefoot enhances ventilation.",
        price: 1499,
        category: "mens",
        color: "red",
        size: 40,
        brand: "Nike",
        rating: 4,
        img: "img/product-1.png",
        altImg: ['img/left-1.png', 'img/right-1.png', 'img/front-1.png', 'img/back-1.png' ],
    },
    {
        id: 2,
        name: "Product Two",
        title: "Mens stylish sneakers",
        description: "The men nike shoe is back and true to its iconic 3-starp design. The leather and woven upper delivers stylish confort while the mesh forefoot enhances ventilation.",
        price: 1499,
        category: "mens",
        color: "red",
        size: 40,
        brand: "Nike",
        rating: 4,
        img: "img/product-2.png.png",
        altImg: ['img/left-2.png', 'img/right-2.png', 'img/front-2.png', 'img/back-2.png' ],
    },
    {
        id: 3,
        name: "Product Three",
        title: "Mens stylish sneakers",
        description: "The men nike shoe is back and true to its iconic 3-starp design. The leather and woven upper delivers stylish confort while the mesh forefoot enhances ventilation.",
        price: 1499,
        category: "mens",
        color: "red",
        size: 40,
        brand: "Nike",
        rating: 4,
        img: "img/product-3.png",
        altImg: ['img/left-3.png', 'img/right-3.png', 'img/front-3.png', 'img/back-3.png' ],
    },
    {
        id: 4,
        name: "Product Four",
        title: "Mens stylish sneakers",
        description: "The men nike shoe is back and true to its iconic 3-starp design. The leather and woven upper delivers stylish confort while the mesh forefoot enhances ventilation.",
        price: 1499,
        category: "mens",
        color: "red",
        size: 40,
        brand: "Nike",
        rating: 4,
        img: "img/product-4.png",
        altImg: ['img/left-4.png', 'img/right-4.png', 'img/front-4.png', 'img/back-4.png' ],
    },
    {
        id: 5,
        name: "Product Five",
        title: "Mens stylish sneakers",
        description: "The men nike shoe is back and true to its iconic 3-starp design. The leather and woven upper delivers stylish confort while the mesh forefoot enhances ventilation.",
        price: 1499,
        category: "mens",
        color: "red",
        size: 40,
        brand: "Nike",
        rating: 4,
        img: "img/product-5.png",
        altImg: ['img/left-5.png', 'img/right-5.png', 'img/front-5.png', 'img/back-5.png' ],
    },
    {
        id: 6,
        name: "Product Six",
        title: "Mens stylish sneakers",
        description: "The men nike shoe is back and true to its iconic 3-starp design. The leather and woven upper delivers stylish confort while the mesh forefoot enhances ventilation.",
        price: 1499,
        category: "mens",
        color: "red",
        size: 40,
        brand: "Nike",
        rating: 4,
        img: "img/product-6.png",
        altImg: ['img/left-6.png', 'img/right-6.png', 'img/front-6.png', 'img/back-6.png' ],
    },
    {
        id: 7,
        name: "Product Seven",
        title: "Mens stylish sneakers",
        description: "The men nike shoe is back and true to its iconic 3-starp design. The leather and woven upper delivers stylish confort while the mesh forefoot enhances ventilation.",
        price: 1499,
        category: "mens",
        color: "red",
        size: 40,
        brand: "Nike",
        rating: 4,
        img: "img/product-7.png",
        altImg: ['img/left-7.png', 'img/right-7.png', 'img/front-7.png', 'img/back-7.png' ],
    },
    {
        id: 8,
        name: "Product Eight",
        title: "Mens stylish sneakers",
        description: "The men nike shoe is back and true to its iconic 3-starp design. The leather and woven upper delivers stylish confort while the mesh forefoot enhances ventilation.",
        price: 1499,
        category: "mens",
        color: "red",
        size: 40,
        brand: "Nike",
        rating: 4,
        img: "img/product-8.png",
        altImg: ['img/left-8.png', 'img/right-8.png', 'img/front-8.png', 'img/back-8.png' ],
    },
    {
        id: 9,
        name: "Product Nine",
        title: "Mens stylish sneakers",
        description: "The men nike shoe is back and true to its iconic 3-starp design. The leather and woven upper delivers stylish confort while the mesh forefoot enhances ventilation.",
        price: 1499,
        category: "mens",
        color: "red",
        size: 40,
        brand: "Nike",
        rating: 4,
        img: "img/product-9.png",
        altImg: ['img/left-9.png', 'img/right-9.png', 'img/front-9.png', 'img/back-9.png' ],
    },
    {
        id: 10,
        name: "Product Ten",
        title: "Mens stylish sneakers",
        description: "The men nike shoe is back and true to its iconic 3-starp design. The leather and woven upper delivers stylish confort while the mesh forefoot enhances ventilation.",
        price: 1499,
        category: "mens",
        color: "red",
        size: 40,
        brand: "Nike",
        rating: 4,
        img: "img/product-10.png",
        altImg: ['img/left-10.png', 'img/right-10.png', 'img/front-10.png', 'img/back-10.png' ],
    },
    {
        id: 11,
        name: "Product Eleven",
        title: "Mens stylish sneakers",
        description: "The men nike shoe is back and true to its iconic 3-starp design. The leather and woven upper delivers stylish confort while the mesh forefoot enhances ventilation.",
        price: 1499,
        category: "mens",
        color: "red",
        size: 40,
        brand: "Nike",
        rating: 4,
        img: "img/product-11.png",
        altImg: ['img/left-11.png', 'img/right-11.png', 'img/front-11.png', 'img/back-11.png' ],
    },
    {
        id: 12,
        name: "Product Twelve",
        title: "Mens stylish sneakers",
        description: "The men nike shoe is back and true to its iconic 3-starp design. The leather and woven upper delivers stylish confort while the mesh forefoot enhances ventilation.",
        price: 1499,
        category: "mens",
        color: "red",
        size: 40,
        brand: "Nike",
        rating: 4,
        img: "img/product-12.png",
        altImg: ['img/left-12.png', 'img/right-12.png', 'img/front-12.png', 'img/back-12.png' ],
    },
    {
        id: 13,
        name: "Product Thirteen",
        title: "Mens stylish sneakers",
        description: "The men nike shoe is back and true to its iconic 3-starp design. The leather and woven upper delivers stylish confort while the mesh forefoot enhances ventilation.",
        price: 1499,
        category: "mens",
        color: "red",
        size: 40,
        brand: "Nike",
        rating: 4,
        img: "img/product-13.png",
        altImg: ['img/left-13.png', 'img/right-13.png', 'img/front-13.png', 'img/back-13.png' ],
    },
    {
        id: 14,
        name: "Product Fourteen",
        title: "Mens stylish sneakers",
        description: "The men nike shoe is back and true to its iconic 3-starp design. The leather and woven upper delivers stylish confort while the mesh forefoot enhances ventilation.",
        price: 1499,
        category: "mens",
        color: "red",
        size: 40,
        brand: "Nike",
        rating: 4,
        img: "img/product-14.png",
        altImg: ['img/left-14.png', 'img/right-14.png', 'img/front-14.png', 'img/back-14.png' ],
    },
    {
        id: 15,
        name: "Product Fifteen",
        title: "Mens stylish sneakers",
        description: "The men nike shoe is back and true to its iconic 3-starp design. The leather and woven upper delivers stylish confort while the mesh forefoot enhances ventilation.",
        price: 1499,
        category: "mens",
        color: "red",
        size: 40,
        brand: "Nike",
        rating: 4,
        img: "img/product-15.png",
        altImg: ['img/left-15.png', 'img/right-15.png', 'img/front-15.png', 'img/back-15.png' ],
    }
        
]


export default products;